version: 2
sphinx:
    configuration: doc/conf.py
    builder: html
    fail_on_warning: false

formats: []

python:
    version: "3.11"
    install:
        - requirements: doc/requirements.txt
        - method: pip
          path: .
        - requirements: requirements_pipelines.txt

# if present, this section is used and python section ignored before sphinx is built
#conda:
#    environment: environment.yml
