version: 2
sphinx:
    configuration: doc/conf.py


formats: []

python:
    version: 3.8
    install:
        - requirements: doc/requirements.txt
        - method: pip
          path: .
        - requirements: requirements_pipelines.txt

# if present, this section is used and python section ignored before sphinx is built
#conda:
#    environment: environment.yml
