name: Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches-ignore: []

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.7, 3.8, 3.9]
      fail-fast: false


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: conda
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies conda
      run: |
        conda install -c conda-forge --quiet 'mamba==0.18.1' python=${{ matrix.python }}
        mamba install -c conda-forge -c bioconda --quiet -y kraken2 shustring 'samtools<1.15' "snpeff" bwa cd-hit 
        conda list | grep ruamel
        conda update ruamel_yaml
    - name: Install sequana with pip
      run: |
        pip install .[testing]
        pip install multiqc==1.11.0
    - name: Test with pytest
      run: |
        pytest --cov-report term --cov=sequana
    - name: coveralls
      run: |
        pip install coveralls
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
