name: Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.7, 3.8, 3.9]
      fail-fast: false


    steps:
    - uses: actions/checkout@v2
    - name: setup mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python }}
        miniforge-variant: Mambaforge
        miniforge-version: latest
        channels: conda-forge,defaults
        activate-environment: testing
        #mamba-version: "*"
        use-mamba: true
    - name:
      shell: bash -l {0}
      run: conda --version
    - name: which python 
      shell: bash -l {0}
      run: which python
    - name: python version 
      shell: bash -l {0}
      run: python --version

    - name: Install dependencies conda
      shell: bash -l {0}
      run: |
        conda info
        #echo $CONDA/bin >> $GITHUB_PATH
        #conda info
        mamba install -c conda-forge -c bioconda --quiet -y kraken2 shustring 'samtools<1.15' "snpeff" bwa cd-hit --name testing
        #conda list | grep ruamel
        #conda update ruamel_yaml
    - name: Install sequana with pip
      shell: bash -l {0}
      run: |
        which pip
        python --version
        which python
        pip install .[testing]
        pip install multiqc==1.11.0
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest --cov-report term --cov=sequana
    - name: coveralls
      shell: bash -l {0}
      run: |
        pip install coveralls
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
